accounts/urls.py
from django.urls import path
from django import urls

#from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('profile/', views.profile, name='accounts'),

]

home/urls.py
from django.urls import path
from django import urls
#from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
     path('', views.index, name='index'),

]

socialblade/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path("users/", include("django.contrib.auth.urls")),  # new
    path("users/", include("users.urls")),  # new
    path("accounts/", include("accounts.urls")),  # new
    path('tinymce/', include('tinymce.urls')),


    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django import urls
#from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
     path('login/', LoginView.as_view, {'template_name': 'users/login.html'}, name = 'login'),
     path('signup/',views.signup, name = 'signup'),
     path('posts/',views.posts, name = 'posts'),
     path('postform/',views.postform, name = 'postform'),
     #was url('path/ views.postform, name = postform)
     #url was changed to path in all url.py files 
     # from django.conf.urls import url was commented out in all url.py files. 
     #Bug fixed


]

accounts/models.py
from distutils.command.upload import upload
from django.db import models
from django.forms import CharField, ImageField

from django.contrib import admin


class profile(models.Model):

  profilepic = models.ImageField(upload_to='images/profilepics', null = True)

def __str__(self):
    return self.title

    
    #display the name of post in django admin

home/models.py
from django.db import models

# Create your models here.

users/models.py
from distutils.command.upload import upload
from django.db import models
from django.forms import CharField, ImageField
from django.forms.fields import DateTimeField
from matplotlib import image
from sqlalchemy import null, true
from django.contrib import admin
from django.conf import settings # needed for importing author function
from tinymce.models import HTMLField
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.contrib import admin

# Create your models here.


class Post(models.Model):
        
    # include title 
    title = models.CharField(null=True, max_length=50)
    
#needs to be made optional blank = True must change jina loging to if single_post_img then post else skip
    image = models.ImageField(upload_to='images/', null = True) 

    quote = HTMLField(null=True) #was models.Textfield

    date = models.DateTimeField(auto_now_add=True, null=True)
    
    #display the name of post in django admin


   

users/forms.py
from dataclasses import fields
import imp
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post
from .models import User
from users import models

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

 
 
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

#edit post form
#class EditForm(forms.ModelForm):
 #   class Meta:
  #      model = Post
   #     fields = '__all__'


        

accounts/views.py
from django.shortcuts import render

# Create your views here.
# this page is where the login page sends you. 
# Create a bio with a picture you can change 
# all your uploads/post 

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.http import HttpResponseRedirect
from matplotlib.style import context
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required()
def profile(request):

    return render(request, 'profile.html' )

home/views.py
from django import views
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from matplotlib.style import context
from matplotlib.style import context
from django.views.generic import *


# Create your views here.
def index(request):
   
    return render(request, 'index.html')
    

users/views.py
from django.contrib.auth import login, authenticate
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from requests import post, request
from users.forms import SignUpForm
from matplotlib.style import context
from django.http import HttpRequest, HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from users.models import Post
#pygeoip to find location of logged in users
#import pygeoip
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)# was UserCreationForm
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('login')  #profile
    else:
        form = SignUpForm() #was UserCreationForm
    return render(request, 'signup.html', {'form': form})
    


#displays post from users

def posts(request):
    userpost = Post.objects.all()
    return render(request, 'posts.html', {'userpost': userpost})


from .forms import PostForm
@login_required()
def postform(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PostForm(request.POST, request.FILES) 
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            form.save()

            form.errors
            return HttpResponseRedirect('/users/posts/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PostForm()

    return render(request, 'postform.html', {'form': form})

accounts/templates/profile.html
<head>
  <title>Social blade</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


</head>
          
  <div class="container justify-content-center">
    <div class="card" style="width:400px">
      <h2>Welcome {{ request.user.username }}</h2>
             <div class="card-body">
        <h4 class="card-title">{{request.user.email}}</h4>
        <p class="card-text">Bio</p>
        <a href="#" class="btn btn-primary">Edit bio</a>
      </div>
    </div>
    </div>

    <div class="container-fluid">
      <h2>Your links</h2>
      <div class="card">
        <div class="card-body">
          <h2><a href="{% url 'index' %}">Home page</a>
    <h2 class="active">
      <a href="{% url 'posts' %}">View the latest Post</a> 
      or      <br>   
      <a href="{% url 'postform' %}">Create new post</a> </h2>
        </div>
      </div>
    </div>
    </div>
  <script>alert("This page is currently being worked on. Some links or buttons may not be functional till production is finished.");</script>

accounts/templates/profilepic.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <title>image upload example</title> 
</head> 
<body> 
    <form method = "post" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit">Upload</button> 
    </form> 
</body> 
</html> 

home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Social</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<style>
  body{
    background-color: white;
    color: black;
  }


</style>
<body>

<!-- menu -->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">TheSocialBlade</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="#">Home</a></li>
        <li><a href="{% url 'posts' %}">Post</a></li>
        <li><a href="{% url 'accounts' %}">My profile</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<!--end menu-->
<div class="content">
<div class="container text-center">
<h1>Welcome</h1><!-- menu -->
<!---
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'signup' %}">Sign up <br></li>
    <br>
    <li class="breadcrumb-item"> <a href="{% url 'posts' %}">View post</li>
    <br>
    <li class="breadcrumb-item">  <a href="{% url 'login' %}">Login</a></li>
    <br>
    <a href="{% url 'accounts' %}">Profile Page</a>

  </ol>
</nav>

end menu-->
 

  <!--card -->
  
</body>

users/templates/postform.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<!--Tiny MCE add on

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js" referrerpolicy=""></script>
<script src="https://cdn.jsdelivr.net/npm/@tinymce/tinymce-jquery@1/dist/tinymce-jquery.min.js"></script> 
-->
</head>
  <style>
    form{
        text-align: center;
    }
</style>
</head>

<body>
<div class = "container lg-6">
<div class = "form-group">

<form enctype="multipart/form-data" method="post">
   {% csrf_token %} 
    
</select></p>
<p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="50" required="" id="id_title" class="form-control"></p>
<p><label for="id_image">Image:</label> <input type="file" name="image" accept="image/*" required="" id="id_image" class="form-control"></p>
<p><label for="id_quote">Quote:</label> <textarea name="quote" cols="40" rows="10" required="" id="id_quote" class="form-control"></textarea></p>
    <input type="submit" value="Submit">
</div>
</form>
<!--
<div>
  <textarea id="tiny"> &lt;p&gt;Welcome to the TinyMCE jQuery example!&lt;/p&gt;</textarea>
</div>
<script>
  $('textarea#tiny').tinymce({
    height: 500,
    menubar: false,
    plugins: [
       'a11ychecker','advlist','advcode','advtable','autolink','checklist','export',
       'lists','link','image','charmap','preview','anchor','searchreplace','visualblocks',
       'powerpaste','fullscreen','formatpainter','insertdatetime','media','table','help','wordcount'
    ],
    toolbar: 'undo redo | a11ycheck casechange blocks | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist checklist outdent indent | removeformat | code table help'
  });
</script>

</div>
-->
</body>

    
   
    

users/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<style>
  img{
    size: 300px;
    height: 300px;
    border-radius: 20px;
  }
</style>
<body>

<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>post</h1>
  <p></p> 
</div>

<div class="container mt-5">
  <div class="row">
  <div class="col-md-6">
      {% for single_post in userpost %}
      <div class="card-header">
        <!-- remove if stataments if code does not work-->
        <h2> {{ single_post.title }} </h2>
     <h3> {{ single_post.quote }}</h3> </div>
      <br>
   <a href = ""> <img src="{{ single_post.image.url }}"> </a><!--url-->
              </div>
      <div class="card-body">
      </div>
      </div>
      </div>
      <div class="col-md-6" style="text-align: center;">
      <em>
      {{ single_post.date }}
      {% endfor %}
    </div>
  </div>
</div>

</body>
</html>

users/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <title>Sign up</title>
</head>
<body>


<style>

.card{
height: auto;
margin-top: 30%;
margin-bottom: auto;
width: auto;
}
.container{
height: 100%;
align-content: center;
color: rgb(3, 3, 3);
}

</style>


{% block content %}
<!--Need to center form
works in mobile but not desktop-->
<div class="container">
  <div class="d-flex justify-content-center h-100">

<div class="col-md-6 text-center">
  <div class="card">
    <div class="card-header">
      <h3>Sign up</h3>
    </div>
  <div class="card-body">

  <form method="post">
    {% csrf_token %}

    <div class="form-group">
   First Name:<br>

   <div class="form-group lg-3" >
   <input name="first_name" type="name" class="form-control" placeholder="first name">
   </div>
   
   Last Name:<br>
   <div class="form-group">
   <input name="last_name" type="name" class="form-control" placeholder="last name">
   </div>

    Username: <br>
    <div class="form-group">
    <input name="username" type="name" class="form-control" placeholder="username">
    </div>
  
    Email: <br>
    <div class="form-group">
    <input name="email" type="email" class="form-control" placeholder="email">
    </div>
    
    Create your password: <br>
    <div class="form-group">
    <input name="password1" type="password" class="form-control" placeholder="password">
    
    </div>
    
    Confirm your password: <br>
    <div class="form-group">
    <input name="password2" type="password" class="form-control" placeholder="confirm password" >
    </div>
      <br>
      <button type="submit" class="btn btn-outline-primary btn-lg btn-block">Sign up</button>

  </form>
</div>
</div>
</div>
</div> 
</div>
</div>
</div>
{% endblock %}

</body>